### ISSUE TITLE
wfMessage->toString() fails on Mediawiki 1_37

### ISSUE THREAD

**Issue by bertrandgorge** [Open-CSP/WikiSearch#18]
Hello,

Here, there seem to be a call to `->toString()` without a parameter, which fails on MW 1_37. Using `->text()` fixes it, it seems.

https://github.com/Open-CSP/WikiSearch/blob/483b1e3dd6fcc0c5ce740cd9ecda7797312a4410/src/WikiSearchHooks.php#L337

**Comment by marijnvanwezel** [comment]
Fixed in b81a1fc.
